### PR TITLE
Option to hide UI

### PR DESCRIPTION
**Pull request by ilyagr**
This is still not in a finished state, but it works, so I thought I'd share. I also mentioned this in https://github.com/blacknon/hwatch/issues/63#issuecomment-1295286866.

To use, try starting `hwatch` with the new `-t` argument. Additionally, try the `Backspace` and `t` keybindings inside `hwatch`. (I keep meaning to change these, but haven't decided what to change them to).

Fixes https://github.com/blacknon/hwatch/issues/63

### CODE REVIEW

**Comment by blacknon** [comment]
Oh, I confirmed that it works!
It is wonderful!

I would like to apply it in version 0.3.8.

**Comment by ilyagr** [comment]
Sorry for disappearing for a bit. I'd like to change the behavior somewhat.
I think the bindings should be `t` and `backspace`, and`t` should be more
similar to the `-t` option.

I think I'm about to have some time to do it. So, I'd prefer it if you
waited a little bit.

**Comment by ilyagr** [comment]
OK, I think I did what I wanted. The toggle for the UI is now `t`, to match the `-t` option. I also added the help messages.

**Comment by ilyagr** [comment]
This now includes https://github.com/blacknon/hwatch/pull/75.

**Review by blacknon — APPROVED** [review]
Wow!!! That is fantastic!
We have checked the operation and reviewed the code. I'm going to merge it into 0.3.8.

**Comment by ilyagr** [comment]
Thanks for taking a look and merging all my PRs! They help me a lot, hopefully they'll be useful for others as well.

**Comment by ilyagr** [comment]
Also, if you celebrate it, Happy New Year! 🎆 🎉

**Pull request merged**
